#!/bin/sh


list="misc-fns.el autofit-frame.el fit-frame.el avoid.el frame-cmds.el frame-fns.el icomplete+.el strings.el thingatpt+.el"


for i in $list
do
	curl -o $i http://www.emacswiki.org/cgi-bin/wiki/download/$i
done



#(require 'auto-fit-frame)
