#!/usr/bin/perl
 
open M, "/tmp/manual.html";
$m = join("", <M>);
close M;


if ($m =~ /(<address>last upd.*?<\/address>)/is)
{
	$i = $1; 
}


$insert =
'<address>Free Software Foundation</address>
'.$i.'
<p> 
	<img src="gnu-head-sm.jpg"
	alt=" [image of the head of a GNU] "
	width="129" height="122" /> 
</p>
';
 
open E, $ARGV[0];
$x = join("", <E>);
close E;
 

if ($x =~ /Emacs version (2[0-9]\.[0-9]*\.?[0-9]*)\.\s/is)
  {
    $version = $1;
  }

if ($x =~ s/(<body>)(.*?)(<div class="node">)/$1 <h1>GNU Emacs Manual<\/h1> $insert $3/is)
{
	$y = $2;
	
	$x =~ s/(<\/body>)/<hr><br>$y$1/is;
}

$x =~ s/For information on extending/<div style="color:red;">For specific additions and deviations from Emacs as described in this manual, please refer to the Aquamacs manual.<\/div>For information on extending/is;

# give legal stuff section title
$x =~ s/^\s*(<ul class="menu">\s*<li>\s*<a accesskey="." href="Distrib\.html.*?Acknowledgments.*?)(<p>\s*General_General_Indexes)/<p>Introduction and Preambles<\/p>\1\2/ism;
#; {
# ;   $y = $1;
# ;   $x =~ s/^\s*(<p>MS-DOS and Windows)/$y$1/ism;
# ;
# ; }
$x =~ s/<\/title>/<\/title>\n<META NAME="AppleTitle" content="Emacs Manual ($version)">\n<META NAME="AppleFont" content="Lucida Grande,Helvetica">\n/is;

# # skip mac os x link
# $x =~ s/^\s*<li>\s*<a accesskey="." href="Mac-OS\.html.*?<li>/<li>/ism;

# # skip DOS link
# $x =~ s/^\s*<li>\s*<a accesskey="." href="MS[^\"]*-DOS\.html.*?<li>/<li>/igsm;

# # skip Windows section
# $x =~ s/^\s*<p>MS-DOS and Windows.*?the ALT key does\.//ism;
 
open E, ">".$ARGV[0]; 

print E $x;
close E;

# must output version
print $version
