#!/bin/sh

P=`pwd`

echo "Give path to manual, e.g. ./convert-emacs-manual ~/Projects/emacs/man"

rm -r /tmp/emanual 2>/dev/null

echo "Using $1 as input file."
cd "$1"
rm -r *.html
make html HTML_OPTS='--html'  # avoid the "--no-split".  HTML_OPTS must be defined with :=
cp -r emacs.html /tmp/emanual  # it's a directory
cp "$1"/index.html /tmp/manual.html # needed for GNU head / last change
cd /tmp/emanual 


cp $P/manual-sources/aquamacs.css /tmp/emanual/

cp $P/manual-sources/gnu-head-sm.jpg /tmp/emanual/

# contains OS X specific information now - don't delete any more
#rm /tmp/emanual/Mac-*.html /tmp/emanual/Windows-*.html
# leave Windows info for now


perl -i -p -e 's/<\/head>/<link rel="stylesheet" href="aquamacs.css" type="text\/css" \/><\/head>/i' /tmp/emanual/*.html
 

$P/convert-emacs-manual-pages /tmp/emanual/*.html
version=`$P/convert-emacs-manual-title /tmp/emanual/index.html`
sed -E 's|<body(.*)>|<body\1><a name="EmacsManualIndex"></a>|' </tmp/emanual/index.html >/tmp/emanual/index2.html
mv /tmp/emanual/index2.html /tmp/emanual/index.html

echo $version >/tmp/emanual/VERSION

rm -r "$P"/../"Aquamacs Help"/"EmacsManual"
mv /tmp/emanual $P/../"Aquamacs Help"/"EmacsManual"
# AppleHelpViewer has trouble when folders have spaces in their names.

#hiutil -C -g -s en -a -f $P/../"EmacsManual/EmacsManual.helpindex" $P/../"EmacsManual"
