#!/bin/sh

# Produces TIFF images with multiple resolutions for high-res icons.

# usage: make-xpm source-dir dest-dir
# ./make-xpm `pwd` `pwd`/build/

EXT=png

P=$1

pushd "$P"
FILES=`ls *.$EXT *.png`
#FILES=`ls copy.*`
popd

cd "$2"


BGCOL='#EAEAEA'

# so ImageMagick can find the freetype library
# text looks extra-ugly otherwise
export DYLD_LIBRARY_PATH="/usr/local/lib"

# Emacs doesn't seem to support masks for PNGs, not even bitmasks

for file in $FILES
do

    BASE=`basename "$file" \.png` 

    # create PNG

# this is less than ideal
# but Emacs doesn't understand alpha

# huge mess following:

# convert "$P/$file" -channel matte -threshold 99% -negate -separate mask.png
# composite -size 500x500 xc:'#BBBBBB'  -compose copy  "$P/$file" blue.png
# composite  "$P/$file" -compose atop blue.png aliased.png
# # now apply the mask
# convert mask.png -fill black -opaque black mask2.png
# #convert mask2.png -blur 6x4 mask3.png
# composite -compose CopyOpacity mask.png aliased.png p.png
# composite -compose atop p.png mask2.png p2.png
# convert p2.png -resize x32 +antialias "$file"

# convert "$P/$file" -channel matte -threshold 99% -negate -separate mask.png
# convert mask.png -fill '#AAAAAA' -opaque black mask2.png
# composite "$P/$file" -compose darken mask2.png -resize x32 "$BASE".xpm

# convert "$P/$file" -channel matte -negate -separate mask.png
# convert mask.png -channel matte -modulate 20 -threshold 50% mask2.png 
# composite -compose CopyOpacity mask.png "$P/$file" $BASE.xpm

#convert  "$P/$file" -resize x32 $file
convert "$P/$file"  -resize x28 -matte -bordercolor none -border 2 $file
convert "$P/$file"  -matte -bordercolor none -border 2 $BASE\@2x.png
convert $file $BASE\@2x.png $BASE.tiff
rm $file $BASE\@2x.png
# tiffutil won't work due to a conflict between libjpeg and libJPEG

#convert p2.png -resize x32  /Applications/Aquamacs\ Emacs.app/Contents/Resources/etc/images/print.png

done
exit

