shortlisp = \
emacs-lisp/byte-run.elc \
emacs-lisp/backquote.elc \
subr.elc \
version.elc \
widget.elc \
custom.elc \
emacs-lisp/map-ynp.elc \
international/mule.elc \
international/mule-conf.elc \
env.elc \
format.elc \
bindings.elc \
window.elc \
files.elc \
emacs-lisp/macroexp.elc \
emacs-lisp/macroexp.elc \
cus-face.elc \
faces.elc \
aquamacs-faces.elc \
button.elc \
emacs-lisp/nadvice.elc \
emacs-lisp/cl-preloaded.elc \
minibuffer.elc \
abbrev.elc \
simple.elc \
help.elc \
jka-cmpr-hook.elc \
epa-hook.elc \
international/mule-cmds.elc \
case-table.elc \
international/charprop.el \
international/characters.elc \
composite.elc \
language/chinese.elc \
language/cyrillic.elc \
language/indian.elc \
language/sinhala.elc \
language/english.elc \
language/ethiopic.elc \
language/european.elc \
language/czech.elc \
language/slovak.elc \
language/romanian.elc \
language/greek.elc \
language/hebrew.elc \
international/cp51932.elc \
international/eucjp-ms.elc \
language/japanese.elc \
language/korean.elc \
language/lao.elc \
language/tai-viet.elc \
language/thai.elc \
language/tibetan.elc \
language/vietnamese.elc \
language/misc-lang.elc \
language/utf-8-lang.elc \
language/georgian.elc \
language/khmer.elc \
language/burmese.elc \
language/cham.elc \
indent.elc \
emacs-lisp/cl-generic.elc \
frame.elc \
startup.elc \
term/tty-colors.elc \
font-core.elc \
facemenu.elc \
emacs-lisp/syntax.elc \
font-lock.elc \
jit-lock.elc \
mouse.elc \
scroll-bar.elc \
select.elc \
emacs-lisp/timer.elc \
isearch.elc \
rfn-eshadow.elc \
menu-bar.elc \
emacs-lisp/lisp.elc \
textmodes/page.elc \
register.elc \
textmodes/paragraphs.elc \
progmodes/prog-mode.elc \
emacs-lisp/lisp-mode.elc \
progmodes/elisp-mode.elc \
textmodes/text-mode.elc \
textmodes/fill.elc \
newcomment.elc \
replace.elc \
emacs-lisp/tabulated-list.elc \
buff-menu.elc \
fringe.elc \
emacs-lisp/regexp-opt.elc \
image.elc \
international/fontset.elc \
dnd.elc \
tool-bar.elc \
dynamic-setting.elc \
x-dnd.elc \
term/common-win.elc \
term/x-win.elc \
term/common-win.elc \
w32-vars.elc \
term/w32-win.elc \
disp-table.elc \
w32-fns.elc \
ls-lisp.elc \
dos-w32.elc \
dos-w32.elc \
dos-fns.elc \
dos-vars.elc \
term/internal.elc \
term/pc-win.elc \
ls-lisp.elc \
disp-table.elc \
term/common-win.elc \
term/ns-win.elc \
mwheel.elc \
emacs-lisp/float-sup.elc \
vc/vc-hooks.elc \
vc/ediff-hook.elc \
uniquify.elc \
electric.elc \
emacs-lisp/eldoc.elc \
cus-start.elc \
tooltip.elc \
emacs-lisp/easymenu.elc \
paren.elc \
timezone.elc \
emacs-lisp/advice.elc \
delsel.elc \
emulation/cua-base.elc \
leim/leim-list.elc \
site-load.elc \
site-init.elc \

