#!/bin/sh

list="avoid.el cl.el files+.el frame-cmds.el frame-fns.el icomplete.el icomplete+.el oneonone.el strings.el thingatpt.el tingatpt+.el def-face-const.el fit-frame.el"


for i in $list
do
	curl -o $i http://www.emacswiki.org/elisp/$i
done


