#!/bin/sh


list="autofit-frame.el fit-frame.el avoid.el frame-cmds.el frame-fns.el icomplete.el icomplete+.el strings.el thingatpt.el thingatpt+ def-face-const.el"


for i in $list
do
	curl -o $i http://www.emacswiki.org/elisp/$i
done



#(require 'auto-fit-frame)
